### ISSUE TITLE
Documentation: Out of Date

### ISSUE THREAD

**Issue by enikebraimoh** [withmono/connect-android#15]
## Summary

I can't find the "*import mono.connect.kit.**"
I followed the documentation and I could only make use of the classes in the "*mono.connect.widget*" 
which says it is deprecated in the docs.
the docs don't provide proper docs on how to use the SDK.

**Comment by ismailnurudeen** [comment]
You using the old dependency version specified in the doc.

Replace  `implementation 'com.github.withmono:mono-connect-android:v1.0.1'` with 
  `implementation 'com.github.withmono:mono-connect-android:v1.1.0'` to resolve the issue.

The README needs to be updated to reflect the new dependency version or a version label could be added at the top.
